/*CREATE TABLE TIPOS_EVENTOS (  --SE refiere a agregar eventos como periodo activo de solicitudes admisiones y perido de subir resultados examenes 
    ID_TIPO_EVENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_EVENTO VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE TIPO_APROBACION (
    ID_APROBACION INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_APROBACION VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT
);


CREATE TABLE TIPO_RECHAZO(
    ID_TIPO_RECHAZO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_RECHAZO VARCHAR(50)
); 

CREATE TABLE TIPOS_REVISORES (
    ID_TIPO_REVISOR INT PRIMARY KEY AUTO_INCREMENT, 
    TIPO_REVISOR VARCHAR(50)
    --se refiere por el caso de si es subcontratado, es empleado o estudiante de la unah
);

CREATE TABLE CENTROS_REGIONALES (
    ID_CENTRO_REGIONAL VARCHAR(20) PRIMARY KEY, --para asignar identificadores con letras que ayudena a identificar el centro 
    NOMBRE_CENTRO VARCHAR(50),
    DEPARTAMENTO VARCHAR(50),
    CIUDAD VARCHAR(50)
);

CREATE TABLE FACULTADES (
    ID_FACULTAD INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_FACULTAD VARCHAR(50)
);

CREATE TABLE TIPO_EXAMENES (
    ID_TIPO_EXAMEN INT PRIMARY KEY AUTO_INCREMENT, 
    TIPO_EXAMEN VARCHAR(50),
    PUNTUACION_MAXIMA INT
);

CREATE TABLE ARCHIVOS (
    ID_ARCHIVO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_ARCHIVO VARCHAR(50),
    TAMANO INT,
    DIMENSION_PIXELES INT,
    URL_ARCHIVO VARCHAR(300)
);

CREATE TABLE ESTADOS_SOLICITUDES (
    ID_ESTADO_SOLICITUD INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE_TIPO_ESTADO VARCHAR(50)
);

/*TABLAS CON LLAVES FORANEAS*/
CREATE TABLE PERSONAS (
    ID_PERSONA INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    DNI VARCHAR(20),
    PASAPORTE VARCHAR(50),
    CORREO_PERSONAL VARCHAR(100),
    TELEFONO INT,
    GRADO_ACADEMICO VARCHAR(300),
    FOREIGN KEY (URL_ARCHIVO_CERTIFICADO) REFERENCES ARCHIVOS(ID_ARCHIVO)
);

CREATE TABLE ASPIRANTES (  --REQUIERE CORRECCION EN EL MODELO RELACIONAL 
    ID_ASPIRANTE INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_REGISTRO DATE,
    URL_TOKEN VARCHAR(300),
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA),
    FOREIGN KEY (ID_CENTRO_REGIONAL) REFERENCES CENTROS_REGIONALES(ID_CENTRO_REGIONAL) --CORERGIR EN EL DIAGRAMA NO ESTA ESTA RELACION ENTRE ASPIRANTE Y CENTRO REGIonal
);


CREATE TABLE CARRERAS (
    ID_CARRERA INT PRIMARY KEY, 
    CODIGO_CARRERA VARCHAR(50),
    NOMBRE_CARRERA VARCHAR(50),
    GRADO_ACADEMICO VARCHAR(50),
    FACULTAD INT,
    FOREIGN KEY (FACULTAD) REFERENCES FACULTADES(ID_FACULTAD)
);

CREATE TABLE HISTORIAL_ACTIVACION_EVENTOS (
    ID_ACTIVACION_EVENTO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_ACTIVACION TIMESTAMP, 
    FECHA_DESACTIVACION TIMESTAMP, 
    ESTADO VARCHAR(50),
    EVENTO INT,
    FOREIGN KEY (EVENTO) REFERENCES TIPOS_EVENTOS(ID_TIPO_EVENTO)

);--RENOMBRAR EN EL DIAGRAMA

CREATE TABLE REVISORES (
    ID_REVISOR INT PRIMARY KEY AUTO_INCREMENT,
    ESTADO_REVISOR BOOLEAN,
    FOREIGN KEY (ID_TIPO_REVISOR) REFERENCES TIPOS_REVISORES(ID_TIPO_REVISOR),
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA)   
);


CREATE TABLE HISTORIAL_SOLICITUDES_REVISADAS (
    ID_INDICE INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_ENVIO TIMESTAMP,
    COMENTARO_REVISOR TEXT,  --CONCIDERAR EN EL BACKEND LA PARTE DE IDENTIFICAR  SI LA SOLICTUD FUE REENVIAS 
    SOLICITUD_REENVIADA BOOLEAN, --CORREGIR NOMBRE 
    FOREIGN KEY (ID_ASPIRANTE) REFERENCES PERSONAS(ID_ASPIRANTE), --COREGIRN EN EL DIAGRAMA 
    FOREIGN KEY (ID_ESTADO_SOLICITUD) REFERENCES ESTADOS_SOLICITUDES(ID_ESTADO_SOLICITUD),-- NO ESTA REFERENCIADA EN EL DIAGRAMA 
    FOREIGN KEY (ID_ACTIVACION_EVENTO) REFERENCES HISTORIAL_ACTIVACION_EVENTOS(ID_ACTIVACION_EVENTO), --RENOMBRAR EN EL DIAGRMAA
    FOREIGN KEY (ID_REVISOR) REFERENCES REVISORES(ID_REVISOR)
);

CREATE TABLE SOLICITUDES_PENDIENTES (
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_RECIBIDA TIMESTAMP,
    FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (ID_REVISOR_ASIGNADO) REFERENCES REVISORES(ID_REVISOR)
);

/*CREACION DE TABLAS CON RELACION DE MUCHOS A MUCHOS O INTERMEDIARIAS */
CREATE TABLE FACULTATES_X_CENTRO (
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTADES(ID_FACULTAD),
    FOREIGN KEY (ID_CENTRO_REGIONAL) REFERENCES CENTROS_REGIONALES(ID_CENTRO_REGIONAL)
);

CREATE TABLE EXAMENES_X_CARRERA (
    ID_INDICE INT PRIMARY KEY AUTO_INCREMENT,
    PUNTAJE_MINIMO INT,
    TIPO_EXAMEN INT,
    CARRERA INT,
    FOREIGN KEY (TIPO_EXAMEN) REFERENCES TIPO_EXAMENES(ID_TIPO_EXAMEN),
    FOREIGN KEY (CARRERA) REFERENCES CARRERAS(ID_CARRERA)
);

CREATE TABLE RESULTADOS_EXAMENES (
    ID_RESULTADO_EXAMEN INT PRIMARY KEY AUTO_INCREMENT,--SE ELIMINA LA RELACOIN CON HISTORIAL ACTIVACIONES , NO TIENE SENTIDO
    PUNTAJE_OBTENIDO INT, 
    ASPIRANTE INT,
    TIPO_EXAMEN INT,
    FOREIGN KEY (ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (TIPO_EXAMEN) REFERENCES TIPO_EXAMENES(ID_TIPO_EXAMEN)
);

CREATE TABLE CORREOS_ENVIADOS (
    ID_CORREO_ENVIADO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_ENVIO TIMESTAMP, 
    ID_RESULTADO_EXAMEN INT,
    ASPIRANTE INT,
    TIPO_APROBACION INT,
    FOREIGN KEY (ID_RESULTADO_EXAMEN) REFERENCES RESULTADOS_EXAMENES(ID_RESULTADO_EXAMEN),
    FOREIGN KEY (ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (TIPO_APROBACION) REFERENCES TIPO_APROBACION(ID_APROBACION)
);


CREATE TABLE CARRERAS_X_ASPIRANTE (
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    ASPIRANTE INT,
    CARRERA VARCAHR(50),
    FOREIGN KEY (ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (CARRERA) REFERENCES CARRERAS(ID_CARRERA)
);*/



create database BD_ADMISIONES;

CREATE TABLE TIPOS_EVENTOS (
    ID_TIPO_EVENTO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_EVENTO VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE TIPO_APROBACION (
    ID_APROBACION INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_APROBACION VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE TIPO_RECHAZO(
    ID_TIPO_RECHAZO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_RECHAZO VARCHAR(50)
);

CREATE TABLE TIPOS_REVISORES (
    ID_TIPO_REVISOR INT PRIMARY KEY AUTO_INCREMENT, 
    CODIGO_TIPO_REVISOR VARCHAR(50),
    TIPO_REVISOR VARCHAR(50)
    -- indica si es subcontratado, empleado o estudiante
);

CREATE TABLE CENTROS_REGIONALES (
    ID_CENTRO_REGIONAL INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_CENTRO VARCHAR(50),
    NOMBRE_CENTRO VARCHAR(50),
    DEPARTAMENTO VARCHAR(50),
    CIUDAD VARCHAR(50)
);

CREATE TABLE FACULTADES (
    ID_FACULTAD INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_FACULTAD VARCHAR(50),
    NOMBRE_FACULTAD VARCHAR(50)
);

CREATE TABLE TIPO_EXAMENES (
    ID_TIPO_EXAMEN INT PRIMARY KEY AUTO_INCREMENT, 
    TIPO_EXAMEN VARCHAR(50),
    PUNTUACION_MAXIMA INT
);

CREATE TABLE ARCHIVOS (
    ID_ARCHIVO INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_ARCHIVO VARCHAR(50),
    TAMANO INT,
    DIMENSION_PIXELES INT,
    URL_ARCHIVO VARCHAR(300)
);

CREATE TABLE ESTADOS_SOLICITUDES (
    ID_ESTADO_SOLICITUD INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRE_TIPO_ESTADO VARCHAR(50)
);

CREATE TABLE PERSONAS (
    ID_PERSONA INT PRIMARY KEY AUTO_INCREMENT, 
    NOMBRES VARCHAR(50),
    APELLIDOS VARCHAR(50),
    DNI VARCHAR(20),
    PASAPORTE VARCHAR(50),
    CORREO_PERSONAL VARCHAR(100),
    TELEFONO INT,
    GRADO_ACADEMICO VARCHAR(300),
    URL_ARCHIVO_CERTIFICADO INT,
    FOREIGN KEY (URL_ARCHIVO_CERTIFICADO) REFERENCES ARCHIVOS(ID_ARCHIVO)
);

CREATE TABLE ASPIRANTES (
    ID_ASPIRANTE INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_REGISTRO DATE,
    URL_TOKEN VARCHAR(300),
    ID_PERSONA INT,
    ID_CENTRO_REGIONAL INT,
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA),
    FOREIGN KEY (ID_CENTRO_REGIONAL) REFERENCES CENTROS_REGIONALES(ID_CENTRO_REGIONAL)
);

CREATE TABLE CARRERAS (
    ID_CARRERA INT PRIMARY KEY AUTO_INCREMENT, 
    CODIGO_CARRERA VARCHAR(50),
    NOMBRE_CARRERA VARCHAR(50),
    GRADO_ACADEMICO VARCHAR(50),
    ID_FACULTAD INT,
    FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTADES(ID_FACULTAD)
);

CREATE TABLE HISTORIAL_ACTIVACION_EVENTOS (
    ID_ACTIVACION_EVENTO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_ACTIVACION TIMESTAMP, 
    FECHA_DESACTIVACION TIMESTAMP, 
    ESTADO VARCHAR(50),
    ID_EVENTO INT,
    FOREIGN KEY (ID_EVENTO) REFERENCES TIPOS_EVENTOS(ID_TIPO_EVENTO)
);

CREATE TABLE REVISORES (
    ID_REVISOR INT PRIMARY KEY AUTO_INCREMENT,
    CODIGO_REVISOR VARCHAR(50),
    ESTADO_REVISOR BOOLEAN,
    ID_TIPO_REVISOR INT,
    ID_PERSONA INT,
    FOREIGN KEY (ID_TIPO_REVISOR) REFERENCES TIPOS_REVISORES(ID_TIPO_REVISOR),
    FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA)
);

CREATE TABLE HISTORIAL_SOLICITUDES_REVISADAS (
    ID_INDICE INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_ENVIO TIMESTAMP,
    COMENTARIO_REVISOR TEXT,
    SOLICITUD_REENVIADA BOOLEAN,
    ID_ASPIRANTE INT,
    ID_ESTADO_SOLICITUD INT,
    ID_ACTIVACION_EVENTO INT,
    ID_REVISOR INT,
    FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (ID_ESTADO_SOLICITUD) REFERENCES ESTADOS_SOLICITUDES(ID_ESTADO_SOLICITUD),
    FOREIGN KEY (ID_ACTIVACION_EVENTO) REFERENCES HISTORIAL_ACTIVACION_EVENTOS(ID_ACTIVACION_EVENTO),
    FOREIGN KEY (ID_REVISOR) REFERENCES REVISORES(ID_REVISOR)
);

CREATE TABLE SOLICITUDES_PENDIENTES (
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_RECIBIDA TIMESTAMP,
    ID_ASPIRANTE INT,
    ID_REVISOR_ASIGNADO INT,
    FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (ID_REVISOR_ASIGNADO) REFERENCES REVISORES(ID_REVISOR)
);

CREATE TABLE FACULTATES_X_CENTRO (
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    ID_FACULTAD INT,
    ID_CENTRO_REGIONAL INT,
    FOREIGN KEY (ID_FACULTAD) REFERENCES FACULTADES(ID_FACULTAD),
    FOREIGN KEY (ID_CENTRO_REGIONAL) REFERENCES CENTROS_REGIONALES(ID_CENTRO_REGIONAL)
);

CREATE TABLE EXAMENES_X_CARRERA (
    ID_INDICE INT PRIMARY KEY AUTO_INCREMENT,
    PUNTAJE_MINIMO INT,
    ID_TIPO_EXAMEN INT,
    ID_CARRERA INT,
    FOREIGN KEY (ID_TIPO_EXAMEN) REFERENCES TIPO_EXAMENES(ID_TIPO_EXAMEN),
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERAS(ID_CARRERA)
);

CREATE TABLE RESULTADOS_EXAMENES (
    ID_RESULTADO_EXAMEN INT PRIMARY KEY AUTO_INCREMENT,
    PUNTAJE_OBTENIDO INT, 
    ID_ASPIRANTE INT,
    ID_TIPO_EXAMEN INT,
    FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (ID_TIPO_EXAMEN) REFERENCES TIPO_EXAMENES(ID_TIPO_EXAMEN)
);

CREATE TABLE CORREOS_ENVIADOS (
    ID_CORREO_ENVIADO INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_ENVIO TIMESTAMP, 
    ID_RESULTADO_EXAMEN INT,
    ID_ASPIRANTE INT,
    ID_TIPO_APROBACION INT,
    FOREIGN KEY (ID_RESULTADO_EXAMEN) REFERENCES RESULTADOS_EXAMENES(ID_RESULTADO_EXAMEN),
    FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (ID_TIPO_APROBACION) REFERENCES TIPO_APROBACION(ID_APROBACION)
);

CREATE TABLE CARRERAS_X_ASPIRANTE (
    ID_REGISTRO INT PRIMARY KEY AUTO_INCREMENT,
    ID_ASPIRANTE INT,
    ID_CARRERA INT,
    FOREIGN KEY (ID_ASPIRANTE) REFERENCES ASPIRANTES(ID_ASPIRANTE),
    FOREIGN KEY (ID_CARRERA) REFERENCES CARRERAS(ID_CARRERA)
);